# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
#
# CodeRabbit configuration for quint-code (Go MCP server).
# Gate G — AI review as validator (STD-030).

language: en-US

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  review_status: true
  commit_status: true
  fail_commit_status: true
  sequence_diagrams: true
  assess_linked_issues: true
  enable_prompt_for_ai_agents: true

  auto_review:
    enabled: true
    drafts: true
    ignore_title_keywords:
      - WIP
      - DO NOT MERGE

  path_filters:
    - "!.quint/**"
    - "!**/*.lock"
    - "!**/fixtures/**"

  path_instructions:
    - path: "**/*.go"
      instructions: |
        Go code review for an MCP server implementing the First Principles
        Framework (FPF). Errors MUST be wrapped with
        fmt.Errorf("context: %w", err) — no swallowed errors (bare _ on
        error returns). Functions SHOULD be under 25 lines. Max 2 levels
        of control flow nesting. MCP JSON-RPC 2.0 responses must include
        id and either result or error, never both.
    - path: "internal/fpf/**"
      instructions: |
        FPF state machine code. Phase transitions MUST follow
        IDLE -> ABDUCTION -> DEDUCTION -> INDUCTION -> DECISION -> IDLE.
        No phase may be skipped. R_eff (assurance score) MUST use min()
        for weakest-link calculation — never average or sum. Flag any
        code that bypasses the FSM or allows out-of-order transitions.
    - path: "docs/**"
      instructions: |
        Documentation. Flag docs referencing function names or APIs that
        appear to have been renamed or removed in the same PR.
    - path: "**/*_test.go"
      instructions: |
        Go test files. FSM transition tests MUST use table-driven format.
        Test names should describe the behavior under test, not the
        function name. Focus on logic coverage, not style.
    - path: ".github/workflows/**"
      instructions: |
        GitHub Actions workflows. Go version must be 1.24+. Actions MUST
        be pinned to SHA or major version tag. No hardcoded secrets.
        Shell scripts MUST use set -euo pipefail.

  tools:
    golangci-lint:
      enabled: true
    shellcheck:
      enabled: true
    gitleaks:
      enabled: true
    ruff:
      enabled: false
    eslint:
      enabled: false
    biome:
      enabled: false

knowledge_base:
  code_guidelines:
    enabled: true
  learnings:
    scope: local
  web_search:
    enabled: true

chat:
  auto_reply: true
