name: Claude Task
description: Structured task for AI-assisted implementation
labels: ["needs-triage"]
body:
  - type: textarea
    id: context
    attributes:
      label: Claude Context
      description: What the AI needs to know
      placeholder: |
        Relevant files, existing behavior, constraints.
        Link to CLAUDE.md sections if applicable.
    validations:
      required: true
  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files
      description: Glob patterns for files that should be modified
      placeholder: |
        src/mcp/*.go
        src/mcp/handlers/*.go
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Use WHEN/THEN format
      placeholder: |
        WHEN: user calls quint_propose with empty hypothesis
        THEN: return error "hypothesis required"
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Technical Constraints
      description: Dependencies, performance limits, compatibility
      placeholder: |
        - Must maintain MCP protocol compatibility
        - Go 1.24 required
  - type: dropdown
    id: size
    attributes:
      label: Size Estimate
      options:
        - "xs (< 50 LOC, 1 file)"
        - "s (50-200 LOC, 1-2 files)"
        - "m (200-500 LOC, 2-3 files)"
        - "l (> 500 LOC — needs decomposition)"
    validations:
      required: true
