version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "QF1003"
